temp/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoicing_Mode__c</fullName>
        <label>Invoicing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>Monthly Invoiced</fullName>
                </value>
                <value>
                    <fullName>COD Net-off</fullName>
                </value>
                <value>
                    <fullName>Agreement execution</fullName>
                </value>
                <value>
                    <fullName>Delhivery Miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/B2B_Price__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>B2B Prices</relationshipLabel>
        <relationshipName>B2B_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>B2B Price</label>
    <nameField>
        <displayFormat>B2B-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Create_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Insurance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoicing_Mode__c</fullName>
        <label>Invoicing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COD Net-off</fullName>
                </value>
                <value>
                    <fullName>Delhivery Miles</fullName>
                </value>
                <value>
                    <fullName>Monthly Invoiced</fullName>
                </value>
                <value>
                    <fullName>Post Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volume_Potential__c</fullName>
        <description>What is the Number of shipments that the client does every Month.
SF - 276</description>
        <label>Delhivery&apos;s Expected Volume (Monthly)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>CFT__c</fullName>
        <label>CFT</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Divisor__c</fullName>
        <formula>27000 /  CFT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Divisor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_liability_per_consignment__c</fullName>
        <label>Maximum Liability for Forward</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Updated_Product_Name__c</fullName>
        <description>Used to replace 500gm with base and Incremental weights present on Opportunity</description>
        <formula>CASE( PricebookEntry.Product2.Name , &quot;Upto 500gms&quot;,  SUBSTITUTE(
&quot;Upto 500gms&quot;, &quot;500&quot;,  Text(Opportunity.Forward_Base__c) )  , &quot;Additional 500gms&quot;,SUBSTITUTE(&quot;Additional 500gms&quot;, &quot;500&quot;,Text(Opportunity.Forward_Incremental__c)), &quot;DTO (500gms)&quot;, SUBSTITUTE(
&quot;DTO (500gms)&quot;, &quot;500&quot;, Text(Opportunity.DTO_Base__c)  ) ,&quot;DTO (Additional 500gms)&quot;,  SUBSTITUTE(&quot;DTO (Additional 500gms)&quot;, &quot;500&quot;,  Text(Opportunity.DTO_Incremental__c)), &quot;RTO (Every 500gms)&quot;, SUBSTITUTE(&quot;RTO (Every 500gms)&quot;, &quot;500&quot;,  Text(Opportunity.RTO__c) ), &quot;Additional 500gms (up to 3kgs)&quot;, SUBSTITUTE(&quot;Additional 500gms (up to 3kgs)&quot;,&quot;500&quot;, TEXT(Opportunity.Forward_Incremental__c) ), &quot;RTO (Every 1000gms)&quot;,SUBSTITUTE(&quot;RTO (Every 1000gms)&quot;,&quot;1000&quot;, TEXT(Opportunity.RTO__c)), &quot;DTO (Every 1000gms)&quot;,SUBSTITUTE(&quot;DTO (Every 1000gms)&quot;,&quot;1000&quot;,TEXT( Opportunity.DTO_Base__c )),&quot;DTO (Add 1000gms)&quot;,SUBSTITUTE(&quot;DTO (Add 1000gms)&quot;,&quot;1000&quot;,TEXT( Opportunity.DTO_Incremental__c )),&quot;DTO (1000gms)&quot;,SUBSTITUTE(&quot;DTO (1000gms)&quot;,&quot;1000&quot;,TEXT( Opportunity.DTO_Base__c )), PricebookEntry.Product2.Name)</formula>
        <label>Updated Product Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>CFT__c</fullName>
        <inlineHelpText>Range 5 to 6</inlineHelpText>
        <label>CFT</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Maximum_liability_per_consignment__c</fullName>
        <label>Maximum Liability for Forward</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

temp/unpackaged/classes/B2BPricingInlineExtension_Test.cls
/*****************************************************************
* Author: Techila Global Services Pvt Ltd.
* Class Name: B2BPricingInlineExtension_Test
* Created Date: 29-June-2017
* Description: Primary test class for B2BPricingInlineExtension
*******************************************************************/


@isTest
public class B2BPricingInlineExtension_Test {
    static testMethod void executePriceTest()
    {
        
  Id rtId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Account').getRecordTypeId();
        Account objAccount= new Account();    
        objAccount.Name='ABC Express For Rishabh';
        objAccount.Registered_Name__c='ABC Express Test';
        objAccount.BillingStreet='EAST street';
        objAccount.BillingCity='Pune';
        objAccount.recordTypeId = rtId1;
        objAccount.BillingState='Maharashtra';
        objAccount.BillingPostalCode='411028';
        objAccount.BillingCountry='India';
        objAccount.Invoicing_Mode__c='Delhivery Miles';
        objAccount.Phone__c = '1236958740';
        objAccount.Email__c = 'test@test.com';
        insert objAccount;   

        
        Contact objContact = new Contact();
        objContact.LastName = 'Test';
        objContact.AccountId = objAccount.id;
        insert objContact;
        
        
        /*List<B2B_Price__c> b2bpriceList = new List<B2B_Price__c>();
        B2B_Price__c objB2BPrice = new B2B_Price__c();
	    objB2BPrice.Source__c='sourceString';
	    insert objB2BPrice;
        b2bpriceList.add(objB2BPrice);*/
        
        
        
        Contract__c objContract = new Contract__c();
	    objContract.Start_Date__c=system.today();
	    insert objContract;
        
        Opportunity objOpportunity=new Opportunity();
        objOpportunity.Name = 'Test222';
        objOpportunity.StageName = 'Proposal Shared';
        objOpportunity.AccountId =objAccount.Id;
        objOpportunity.CloseDate = system.today(); 
        objOpportunity.Create_Opportunity__c = true;
        objOpportunity.Volume_Potential__c= 100;
        objOpportunity.Create_Opportunity__c = true;
        insert objOpportunity;
        
       
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 objproduct = new Product2(
            Name = 'B2B 5*5',
            ProductCode = 'Pro-X',
            isActive = true);        
        insert objproduct;
        
        PricebookEntry objpbEntry = new PricebookEntry( 
            Pricebook2Id = pricebookId,
            Product2Id = objproduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert objpbEntry;
        
        OpportunityLineItem objoli = new OpportunityLineItem();
        objoli.OpportunityId = objOpportunity.Id;
        objoli.Quantity = 5;
        objoli.PricebookEntryId = objpbEntry.Id;
        objoli.TotalPrice = objpbEntry.UnitPrice * objpbEntry.UnitPrice;
        objoli.Maximum_liability_per_consignment__c = 10;
        objoli.Insurance__c = 15;
        objoli.CFT__c = 5;
        objoli.IsActive__c = true;
        
        insert objoli;
        
   
        // Insert B2B
        List<B2B_Price__c>  B2BpriceList= new List<B2B_Price__c> ();
        List<String> sourceList = new List<String>();
        sourceList.add('North');
        sourceList.add('West');
        sourceList.add('South');
        sourceList.add('East');
        sourceList.add('North East');
        
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<5;j++){
                B2B_Price__c objB2Bprice= new B2B_Price__c();
                objB2Bprice.Amount__c=15;
                objB2Bprice.Product__c=objProduct.Id;
                objB2Bprice.Source__c=sourceList[i];    
                objB2Bprice.Destination__c=sourceList[j];   
                objB2Bprice.Opportunity_Line_Item_Id__c=objoli.Id;
                B2BpriceList.add(objB2Bprice);
            }
            
        }
        insert B2BpriceList;
       
        ApexPages.currentPage().getParameters().put('id',objOpportunity.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(objOpportunity);
        B2BPricingInlineExtension objcontroller=new B2BPricingInlineExtension(sc);
        objcontroller.downloadContractAgreement();
        objcontroller.downloadAddendum();
        objcontroller.generatePricingPDFB2B();
        objcontroller.getPrintView();
        
        ApexPages.currentPage().getParameters().put('ContactId',objContact.Id);
        ApexPages.StandardController sc2 = new ApexPages.StandardController(objContact);
        B2BPricingInlineExtension objcontroller2=new B2BPricingInlineExtension(sc2);
        
        ApexPages.currentPage().getParameters().put('ContractId',objContract.Id);
        ApexPages.StandardController sc3 = new ApexPages.StandardController(objContract);
        B2BPricingInlineExtension objcontroller3=new B2BPricingInlineExtension(sc3);
    }    
    
    static testMethod void executePriceTestone()
    {
         Id rtId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Account').getRecordTypeId();
        Account objAccount= new Account();    
        objAccount.Name='ABC Express For Rishabh';
        objAccount.Registered_Name__c='ABC Express Test';
        objAccount.BillingStreet='EAST street';
        objAccount.BillingCity='Pune';
        objAccount.recordTypeId = rtId1;
        objAccount.BillingState='Maharashtra';
        objAccount.BillingPostalCode='411028';
        objAccount.BillingCountry='India';
        objAccount.Invoicing_Mode__c='Delhivery Miles';
        objAccount.Phone__c = '1236958740';
        objAccount.Email__c = 'test@test.com';
        insert objAccount;   

        
        Contact objContact = new Contact();
        objContact.LastName = 'Test';
        objContact.AccountId = objAccount.id;
        insert objContact;
        
        
        /*List<B2B_Price__c> b2bpriceList = new List<B2B_Price__c>();
        B2B_Price__c objB2BPrice = new B2B_Price__c();
	    objB2BPrice.Source__c='sourceString';
	    insert objB2BPrice;
        b2bpriceList.add(objB2BPrice);*/
        
        
        
        Contract__c objContract = new Contract__c();
	    objContract.Start_Date__c=system.today();
	    insert objContract;
        
        Opportunity objOpportunity=new Opportunity();
        objOpportunity.Name = 'Test222';
        objOpportunity.StageName = 'Proposal Shared';
        objOpportunity.AccountId =objAccount.Id;
        objOpportunity.CloseDate = system.today(); 
        objOpportunity.Create_Opportunity__c = true;
        objOpportunity.Volume_Potential__c= 100;
        objOpportunity.Create_Opportunity__c = true;
        insert objOpportunity;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 objproduct = new Product2(
            Name = 'B2B 15*15',
            ProductCode = 'Pro-X',
            isActive = true);
        insert objproduct;
        
        PricebookEntry objpbEntry = new PricebookEntry( 
            Pricebook2Id = pricebookId,
            Product2Id = objproduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert objpbEntry;
        
        OpportunityLineItem objoli = new OpportunityLineItem();
        objoli.OpportunityId = objOpportunity.Id;
        objoli.Quantity = 5;
        objoli.PricebookEntryId = objpbEntry.Id;
        objoli.TotalPrice = objpbEntry.UnitPrice * objpbEntry.UnitPrice;
        objoli.Maximum_liability_per_consignment__c = 10;
        objoli.Insurance__c = 15;
        objoli.CFT__c = 5;
        //objoli.Divisor__c = 8;
        objoli.IsActive__c = true;
        // objoli.Updated_Product_Name__c=objproduct.Name;
        insert objoli;
        
        // Insert B2B
        List<B2B_Price__c>  B2BpriceList= new List<B2B_Price__c> ();
        List<String> sourceList = new List<String>();
        sourceList.add('North');
        sourceList.add('West');
        sourceList.add('South');
        sourceList.add('East');
        sourceList.add('North East');
        
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<5;j++){
                B2B_Price__c objB2Bprice= new B2B_Price__c();
                objB2Bprice.Amount__c=15;
                objB2Bprice.Product__c=objProduct.Id;
                objB2Bprice.Source__c=sourceList[i];    
                objB2Bprice.Destination__c=sourceList[j];   
                objB2Bprice.Opportunity_Line_Item_Id__c=objoli.Id;
                B2BpriceList.add(objB2Bprice);
            }
            
        }
        insert B2BpriceList;
        
        ApexPages.currentPage().getParameters().put('id',objOpportunity.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(objOpportunity);
        B2BPricingInlineExtension objcontroller=new B2BPricingInlineExtension(sc);
        
    }    
    
    static testMethod void executePriceTestoneB2B()
    {
         Id rtId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Account').getRecordTypeId();
        Account objAccount= new Account();    
        objAccount.Name='ABC Express For Rishabh';
        objAccount.Registered_Name__c='ABC Express Test';
        objAccount.BillingStreet='EAST street';
        objAccount.BillingCity='Pune';
        objAccount.recordTypeId = rtId1;
        objAccount.BillingState='Maharashtra';
        objAccount.BillingPostalCode='411028';
        objAccount.BillingCountry='India';
        objAccount.Invoicing_Mode__c='Delhivery Miles';
        objAccount.Phone__c = '1236958740';
        objAccount.Email__c = 'test@test.com';
        insert objAccount;   

        
        Contact objContact = new Contact();
        objContact.LastName = 'Test';
        objContact.AccountId = objAccount.id;
        insert objContact;
        
        
        /*List<B2B_Price__c> b2bpriceList = new List<B2B_Price__c>();
        B2B_Price__c objB2BPrice = new B2B_Price__c();
	    objB2BPrice.Source__c='sourceString';
	    insert objB2BPrice;
        b2bpriceList.add(objB2BPrice);*/
        
        
        
        Contract__c objContract = new Contract__c();
	    objContract.Start_Date__c=system.today();
	    insert objContract;
        
        Opportunity objOpportunity=new Opportunity();
        objOpportunity.Name = 'Test222';
        objOpportunity.StageName = 'Proposal Shared';
        objOpportunity.AccountId =objAccount.Id;
        objOpportunity.CloseDate = system.today(); 
        objOpportunity.Create_Opportunity__c = true;
        objOpportunity.Volume_Potential__c= 100;
        objOpportunity.Create_Opportunity__c = true;
        insert objOpportunity;
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 objproduct = new Product2(
            Name = 'B2B 6*6',
            ProductCode = 'Pro-X',
            isActive = true);
        insert objproduct;
        
        PricebookEntry objpbEntry = new PricebookEntry( 
            Pricebook2Id = pricebookId,
            Product2Id = objproduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert objpbEntry;
        
        OpportunityLineItem objoli = new OpportunityLineItem();
        objoli.OpportunityId = objOpportunity.Id;
        objoli.Quantity = 5;
        objoli.PricebookEntryId = objpbEntry.Id;
        objoli.TotalPrice = objpbEntry.UnitPrice * objpbEntry.UnitPrice;
        objoli.Maximum_liability_per_consignment__c = 10;
        objoli.Insurance__c = 15;
        objoli.CFT__c = 5;
        //objoli.Divisor__c = 8;
        objoli.IsActive__c = true;
        // objoli.Updated_Product_Name__c=objproduct.Name;
        insert objoli;
        
        // Insert B2B
        List<B2B_Price__c>  B2BpriceList= new List<B2B_Price__c> ();
        List<String> sourceList = new List<String>();
        sourceList.add('North');
        sourceList.add('West');
        sourceList.add('South');
        sourceList.add('East');
        sourceList.add('North East');
        
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<5;j++){
                B2B_Price__c objB2Bprice= new B2B_Price__c();
                objB2Bprice.Amount__c=15;
                objB2Bprice.Product__c=objproduct.Id;
                objB2Bprice.Source__c=sourceList[i];    
                objB2Bprice.Destination__c=sourceList[j];   
                objB2Bprice.Opportunity_Line_Item_Id__c=objoli.Id;
                B2BpriceList.add(objB2Bprice);
            }
            
        }
        insert B2BpriceList;
        
        
        ApexPages.currentPage().getParameters().put('id',objOpportunity.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(objOpportunity);
        B2BPricingInlineExtension objcontroller=new B2BPricingInlineExtension(sc);
        
    }
    //for B2B 14*14
    static testMethod void executePriceTestoneB2B14()
    {
         Id rtId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Account').getRecordTypeId();
        Account objAccount= new Account();    
        objAccount.Name='ABC Express For Rishabh';
        objAccount.Registered_Name__c='ABC Express Test';
        objAccount.BillingStreet='EAST street';
        objAccount.BillingCity='Pune';
        objAccount.recordTypeId = rtId1;
        objAccount.BillingState='Maharashtra';
        objAccount.BillingPostalCode='411028';
        objAccount.BillingCountry='India';
        objAccount.Invoicing_Mode__c='Delhivery Miles';
        objAccount.Phone__c = '1236958740';
        objAccount.Email__c = 'test@test.com';
        insert objAccount;   

        
        Contact objContact = new Contact();
        objContact.LastName = 'Test';
        objContact.AccountId = objAccount.id;
        insert objContact;
        
        
        /*List<B2B_Price__c> b2bpriceList = new List<B2B_Price__c>();
        B2B_Price__c objB2BPrice = new B2B_Price__c();
	    objB2BPrice.Source__c='sourceString';
	    insert objB2BPrice;
        b2bpriceList.add(objB2BPrice);*/
        
        
        
        Contract__c objContract = new Contract__c();
	    objContract.Start_Date__c=system.today();
	    insert objContract;
        
        Opportunity objOpportunity=new Opportunity();
        objOpportunity.Name = 'Test222';
        objOpportunity.StageName = 'Proposal Shared';
        objOpportunity.AccountId =objAccount.Id;
        objOpportunity.CloseDate = system.today(); 
        objOpportunity.Create_Opportunity__c = true;
        objOpportunity.Volume_Potential__c= 100;
        objOpportunity.Create_Opportunity__c = true;
        insert objOpportunity;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 objproduct = new Product2(
            Name = 'B2B 14*14',
            ProductCode = 'Pro-X',
            isActive = true);
        insert objproduct;
        
        PricebookEntry objpbEntry = new PricebookEntry( 
            Pricebook2Id = pricebookId,
            Product2Id = objproduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert objpbEntry;
        
        OpportunityLineItem objoli = new OpportunityLineItem();
        objoli.OpportunityId = objOpportunity.Id;
        objoli.Quantity = 5;
        objoli.PricebookEntryId = objpbEntry.Id;
        objoli.TotalPrice = objpbEntry.UnitPrice * objpbEntry.UnitPrice;
        objoli.Maximum_liability_per_consignment__c = 10;
        objoli.Insurance__c = 15;
        objoli.CFT__c = 5;
        //objoli.Divisor__c = 8;
        objoli.IsActive__c = true;
        // objoli.Updated_Product_Name__c=objproduct.Name;
        insert objoli;
        
        // Insert B2B
        List<B2B_Price__c>  B2BpriceList= new List<B2B_Price__c> ();
        List<String> sourceList = new List<String>();
        sourceList.add('North');
        sourceList.add('West');
        sourceList.add('South');
        sourceList.add('East');
        sourceList.add('North East');
        
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<5;j++){
                B2B_Price__c objB2Bprice= new B2B_Price__c();
                objB2Bprice.Amount__c=15;
                objB2Bprice.Product__c=objProduct.Id;
                objB2Bprice.Source__c=sourceList[i];    
                objB2Bprice.Destination__c=sourceList[j];   
                objB2Bprice.Opportunity_Line_Item_Id__c=objoli.Id;
                B2BpriceList.add(objB2Bprice);
            }
            
        }
        insert B2BpriceList;
        
        ApexPages.currentPage().getParameters().put('id',objOpportunity.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(objOpportunity);
        B2BPricingInlineExtension objcontroller=new B2BPricingInlineExtension(sc);
        
    }
    
}