temp/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Invoicing_Mode__c</fullName>
        <label>Invoicing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>Monthly Invoiced</fullName>
                </value>
                <value>
                    <fullName>COD Net-off</fullName>
                </value>
                <value>
                    <fullName>Agreement execution</fullName>
                </value>
                <value>
                    <fullName>Delhivery Miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Services Agreement</fullName>
                </value>
                <value>
                    <fullName>GST Agreement</fullName>
                </value>
                <value>
                    <fullName>Gst Agreement(FTL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Create_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Forward_Base__c</fullName>
        <defaultValue>CASE($RecordType.DeveloperName, &apos;Express_Shipping&apos;, 500, &apos;Standard_Shipping&apos;, 500,500)</defaultValue>
        <label>Forward Base (in grams)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoicing_Mode__c</fullName>
        <label>Invoicing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COD Net-off</fullName>
                </value>
                <value>
                    <fullName>Delhivery Miles</fullName>
                </value>
                <value>
                    <fullName>Monthly Invoiced</fullName>
                </value>
                <value>
                    <fullName>Post Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sites_Listed_On__c</fullName>
        <label>Sites Listed On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volume_Potential__c</fullName>
        <description>What is the Number of shipments that the client does every Month.
SF - 276</description>
        <label>Delhivery&apos;s Expected Volume (Monthly)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/unpackaged/classes/C2CAgreementPDFControllerTest.cls
@IsTest
public class C2CAgreementPDFControllerTest {
    
    public static testMethod void testC2CPDF()
    {
         Account objAccount= new Account();
        objAccount.Name='Test Account';
        objAccount.Invoicing_Mode__c='Prepaid';
        objAccount.Phone__c='7798989898';
        insert objAccount;
        
        // Contacts created to send mail and associate it with Opportunity
        Contact objContact= new Contact();
        objContact.FirstName='Pradeep';
        objContact.LastName='Gore';
        objContact.Email='test1@techilaservices.com';
        objContact.AccountId=objAccount.Id;
        insert objContact;
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name='Test opportunity1';
        objOpportunity.StageName='Commercials Agreed';
        objOpportunity.Description='test';
        objOpportunity.Sites_Listed_On__c='test1';
        objOpportunity.CloseDate=System.today();
        objOpportunity.Forward_Base__c=500;
        objOpportunity.AccountId=objAccount.Id;
        objOpportunity.Volume_Potential__c=23.3;
        objOpportunity.Create_Opportunity__c = true;
        
        insert objOpportunity;
        Contract__c objContract3 = new Contract__c();
        objContract3.Type__c= 'B2B';
        objContract3.Opportunity__c=objOpportunity.Id;
        objContract3.Start_Date__c=system.today();
        objContract3.Effective_Date__c=system.today();
        objContract3.End_Date__c=system.today();
        insert objContract3;
        
        List<OpportunityContactRole> OCRList= new List<OpportunityContactRole>();
        OpportunityContactRole objOCR1= new OpportunityContactRole();
        objOCR1.ContactId=objContact.Id;
        objOCR1.OpportunityId=objOpportunity.Id;
        objOCR1.Role='Signing Authority';
        objOCR1.IsPrimary=true;
        OCRList.add(objOCR1);
        insert OCRList;
        
        Test.startTest();
        ApexPages.currentpage().getParameters().put('id',objOpportunity.Id);
        ApexPages.StandardController sc= new ApexPages.StandardController(objOpportunity);
        C2CAgreementPDFController objController= new C2CAgreementPDFController(sc);    
        Test.stopTest();  
    }
}