temp/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RTGS_IFSC_code__c</fullName>
        <label>RTGS/ IFSC code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Client_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Large Horizontals</fullName>
                </value>
                <value>
                    <fullName>Vertical Leaders</fullName>
                </value>
                <value>
                    <fullName>Long tail e-tailers and platform sellers</fullName>
                </value>
                <value>
                    <fullName>Marketplace Vendors</fullName>
                </value>
                <value>
                    <fullName>Independent SMBs</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>FMCG</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Health,Pharma</fullName>
                    <label>Health, Pharma</label>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Aggregator</fullName>
                </value>
                <value>
                    <fullName>Ecommerce Horizontal</fullName>
                </value>
                <value>
                    <fullName>Ecommerce Vertical</fullName>
                </value>
                <value>
                    <fullName>Consumer Durables</fullName>
                </value>
                <value>
                    <fullName>Industrials</fullName>
                </value>
                <value>
                    <fullName>Auto Ancillaries &amp; Tyres</fullName>
                </value>
                <value>
                    <fullName>Health and Pharma</fullName>
                </value>
                <value>
                    <fullName>Books and Stationery</fullName>
                </value>
                <value>
                    <fullName>Textiles</fullName>
                </value>
                <value>
                    <fullName>Lubricants &amp; Paints</fullName>
                </value>
                <value>
                    <fullName>Furniture and White Goods</fullName>
                </value>
                <value>
                    <fullName>Etail Longtail</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Aggregator/Co-loader</fullName>
                </value>
                <value>
                    <fullName>C2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

temp/unpackaged/objects/Customer_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>CL_PANEL_User_Name__c</fullName>
        <label>CL PANEL User Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Desired_HQ_Name__c</fullName>
        <label>Desired HQ Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type__c</fullName>
        <formula>Opportunity__r.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_SubCategory__c</fullName>
        <formula>Opportunity__r.Sub_Category_Formula__c</formula>
        <label>Opportunity SubCategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Onboardings</relationshipLabel>
        <relationshipName>Customer_Onboardings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RTGS_IFSC_code__c</fullName>
        <label>RTGS/ IFSC code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Customer Onboarding</label>
    <nameField>
        <displayFormat>COB-{0000000}</displayFormat>
        <label>Customer Onboarding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Onboardings</pluralLabel>
    <recordTypes>
        <fullName>Fulfillment</fullName>
        <active>true</active>
        <description>For Fulfillment Opportunities</description>
        <label>Fulfillment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Client_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Large Horizontals</fullName>
                </value>
                <value>
                    <fullName>Vertical Leaders</fullName>
                </value>
                <value>
                    <fullName>Long tail e-tailers and platform sellers</fullName>
                </value>
                <value>
                    <fullName>Marketplace Vendors</fullName>
                </value>
                <value>
                    <fullName>Independent SMBs</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>FMCG</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Health,Pharma</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Aggregator</fullName>
                </value>
                <value>
                    <fullName>C2C</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Mail-Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/COB_TriggerHandler.cls
public class COB_TriggerHandler 
{
// Method to create unique Desired HQ name in COB compare with Account External Ids
public static void insertHqNameMethod(List<Customer_Onboarding__c> newonboarding)
{   
    system.debug('-----insertHqmethod------');
    List<Account> listofallAccount = [select id,recordType.Name ,External_Id__c ,Name, Registered_Name__c  from Account where recordType.Name ='Service Account' and Registered_Name__c !='' Limit 30000];
    Set<String> setOfaccExtId = new Set<String>();//Fill Unique External_Id
    
    //fetch all account to check duplicate External_Id
    for(Account eachAcc : listofallAccount){
        setOfaccExtId.add(eachAcc.External_Id__c);
    }
    
    List<Customer_Onboarding__c> listofallcob = [Select id,Desired_HQ_Name__c,createdDate from Customer_Onboarding__c  order By createdDate Desc Limit 10000 ];
    
    //fetch all COB to check duplicate desired HQ
    for(Customer_Onboarding__c eachHqName : listofallcob){
        setOfaccExtId.add(eachHqName.Desired_HQ_Name__c);
    }
    setOfaccExtId.remove(null);
    String CustomlabelDate = label.COB_FilterDate;
    List<String> tempDate = CustomlabelDate.split('-');
    Date custDate = Date.valueOf(date.parse(tempDate [2]+'/'+tempDate [1]+'/'+tempDate [0]));
    //Iterate through each Trigger.new of COB
    for(Customer_Onboarding__c eachCOB : newonboarding ){
            
            system.debug('---eachCOBdate---'+eachCOB.createdDate);
            system.debug('--eachCOB.Opportunity_Name__c--'+eachCOB.Opportunity_Name__c);
            If( eachCOB.Opportunity_Name__c!=null && eachCOB.Opportunity_Record_Type__c != null )
            {  
                String HqName = eachCOB.Opportunity_Name__c.substringbefore('-').toUpperCase().replaceAll('[^a-zA-Z0-9 ]','');// convert to upper case and remove special character
                List<String> tempHqName = HqName.split(' ');
                String finalHqname ='';
                Boolean isDuplicate = true ; // Check External id is Duplicate with COB Desired HQ Name
                System.debug('Value of Each COB Opp Records Type is '+eachCOB.Opportunity_Record_Type__c);
                System.debug('Value of Their Respective Sub Category is '+eachCOB.Opportunity__r.Sub_Category__c);
                // Create Unique Desire HQ Name based on spaces present in External Id Before '-'
                for(integer i=0 ; i< tempHqName.size() ; i++){
                    if(isDuplicate ){  
                        finalHqname = finalHqname.substringbefore(' '); // to remove record type name through each iteration
                        finalHqname = finalHqname+tempHqName[i];
                        if(finalHqname.length()>20){
                            finalHqname = finalHqname.substring(0, 19);
                        }
                        // Add suffix with record type name
                        if(eachCOB.Opportunity_Record_Type__c.contains('B2B')){
                            finalHqname = finalHqname +' B2B';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Standard')){
                            finalHqname = finalHqname +' SURFACE';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('SaaS')){
                            finalHqname = finalHqname +' SAAS';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Express')){
                            finalHqname = finalHqname +' EXPRESS';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Fulfillment')){
                            finalHqname = finalHqname +' FULFILL';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('B2R')){
                            finalHqname = finalHqname +' B2R';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Cash')){
                            finalHqname = finalHqname +' CASH';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Customer')){
                            finalHqname = finalHqname +' CUSTACQ';
                        }                       
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Heavy')){
                            finalHqname = finalHqname +' HEAVY';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Hyperlocal')){
                            finalHqname = finalHqname +' HYLOCAL';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('International')){
                            finalHqname = finalHqname +' INTL';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('MPP')){
                            finalHqname = finalHqname +' MPP';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('Others')){
                            finalHqname = finalHqname +' OTHER';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('X Border Large')){
                            finalHqname = finalHqname +' XBL';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('X Border Medium')){
                            finalHqname = finalHqname +' XBM';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.contains('X Border Small')){
                            finalHqname = finalHqname +' XBS';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.Contains('C2C') && eachCOB.Opportunity_SubCategory__c=='Franchise')
                        {
                            finalHqname = finalHqname +' FRANCHISE';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.Contains('C2C') && eachCOB.Opportunity_SubCategory__c=='Mail-Room')
                        {
                            finalHqname = finalHqname +' MAILROOM';
                        }
                        else if(eachCOB.Opportunity_Record_Type__c.Contains('C2C') && eachCOB.Opportunity_SubCategory__c=='C2C')
                        {
                            finalHqname = finalHqname +' C2C';
                        }
                        isDuplicate = setOfaccExtId.contains(finalHqname); //False when no duplicate found in case of true repeat each iteration 
                        If(finalHqname.substringbefore(' ').length()<5){
                            isDuplicate = true;
                        }
                    }
                    
                }
                
                //If Desired HQ Name is not present
                
                system.debug('Enter whern hq name blank'); 
                system.debug('---isDuplicate---'+isDuplicate);
                system.debug('--finalHqname---'+finalHqname);
                If(isDuplicate){
                    // when no unique found through loop iteration
                    eachCOB.Desired_HQ_Name__c = '';
                    //eachCOB.isDuplicate_DesiredHq__c = true;
                    If(eachCOB.RTGS_IFSC_code__c!=null && eachCOB.RTGS_IFSC_code__c!=''){
                        eachCOB.RTGS_IFSC_code__c =eachCOB.RTGS_IFSC_code__c.toUpperCase();
                    }
                }
                else {
                    // when unique desire HQ name is found
                    eachCOB.Desired_HQ_Name__c = finalHqname;
                    eachCOB.CL_PANEL_User_Name__c = finalHqname.replaceAll(' ','');
                    If(eachCOB.RTGS_IFSC_code__c!=null && eachCOB.RTGS_IFSC_code__c!=''){
                        eachCOB.RTGS_IFSC_code__c =eachCOB.RTGS_IFSC_code__c.toUpperCase();
                    }
                    
                }
            }
            
    }
}

public static void updateHqNameMethod(List<Customer_Onboarding__c> newonboarding,Map<Id,Customer_Onboarding__c> oldMap)
{
    system.debug('--inside updatehqnamemethod--');
    List<Customer_Onboarding__c> listofdiffhqCOB = new List<Customer_Onboarding__c>();
    Set<Id> setofnew = new Set<Id>();
    For(Customer_Onboarding__c eachnew : newonboarding)
    {
        If(eachnew.RTGS_IFSC_code__c!=null && eachnew.RTGS_IFSC_code__c!=''){
            eachnew.RTGS_IFSC_code__c=eachnew.RTGS_IFSC_code__c.toUpperCase();
        }
        IF(eachnew.Desired_HQ_Name__c != oldMap.get(eachnew.Id).Desired_HQ_Name__c)
        {
            listofdiffhqCOB.add(eachnew);
            setofnew.add(eachnew.id);
        }
    }
    
    If(listofdiffhqCOB != null && listofdiffhqCOB.size()>0)
    {
        system.debug('-----inside updateHqmethod hqdifferent------');
        List<Account> listofallAccount = [select id,recordType.Name ,External_Id__c ,Name, Registered_Name__c  from Account where recordType.Name ='Service Account' and Registered_Name__c !=''];
          
        Set<String> setOfaccExtId = new Set<String>();//Fill Unique External_Id
       
        //fetch all account to check duplicate External_Id
        for(Account eachAcc : listofallAccount){
            setOfaccExtId.add(eachAcc.External_Id__c);
        }
        
        List<Customer_Onboarding__c> listofallcob = [Select id,Desired_HQ_Name__c,createdDate from Customer_Onboarding__c where id NOT IN: setofnew order By createdDate Desc Limit 10000 ];
        //fetch all COB to check duplicate desired HQ
        for(Customer_Onboarding__c eachHqName : listofallcob){
            setOfaccExtId.add(eachHqName.Desired_HQ_Name__c);
        }
        setOfaccExtId.remove(null);
        String CustomlabelDate = label.COB_FilterDate;
        List<String> tempDate = CustomlabelDate.split('-');
        Date custDate = Date.valueOf(date.parse(tempDate [2]+'/'+tempDate [1]+'/'+tempDate [0]));
        for(Customer_Onboarding__c eachCOB : listofdiffhqCOB ){
            If(eachCOB.createdDate >= custDate && setOfaccExtId.contains(eachCOB.Desired_HQ_Name__c)){
                    // when no unique found through loop iteration
                    system.debug('--setofaccextId----'+setOfaccExtId);
                    eachCOB.addError(label.COB_DesireHQError);
                    
                }
        }

    }
}
}