temp/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoicing_Mode__c</fullName>
        <label>Invoicing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prepaid</fullName>
                </value>
                <value>
                    <fullName>Monthly Invoiced</fullName>
                </value>
                <value>
                    <fullName>COD Net-off</fullName>
                </value>
                <value>
                    <fullName>Agreement execution</fullName>
                </value>
                <value>
                    <fullName>Delhivery Miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/B2B_Price__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>B2B Price</label>
    <nameField>
        <displayFormat>B2B-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Category__c.object
<CustomObject>
    <description>Product Categories</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

temp/unpackaged/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Viewed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Services Agreement</fullName>
                </value>
                <value>
                    <fullName>GST Agreement</fullName>
                </value>
                <value>
                    <fullName>Gst Agreement(FTL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Co_Loader__c</fullName>
        <label>Co Loader</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Forward_Base__c</fullName>
        <defaultValue>CASE($RecordType.DeveloperName, &apos;Express_Shipping&apos;, 500, &apos;Standard_Shipping&apos;, 500,500)</defaultValue>
        <label>Forward Base (in grams)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoicing_Mode__c</fullName>
        <label>Invoicing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COD Net-off</fullName>
                </value>
                <value>
                    <fullName>Delhivery Miles</fullName>
                </value>
                <value>
                    <fullName>Monthly Invoiced</fullName>
                </value>
                <value>
                    <fullName>Post Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sites_Listed_On__c</fullName>
        <label>Sites Listed On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Corporate Approved</fullName>
                </value>
                <value>
                    <fullName>Corporate Rejected</fullName>
                </value>
                <value>
                    <fullName>Client Approved</fullName>
                </value>
                <value>
                    <fullName>Client Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume_Potential__c</fullName>
        <description>What is the Number of shipments that the client does every Month.
SF - 276</description>
        <label>Delhivery&apos;s Expected Volume (Monthly)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Intra_City__c</fullName>
        <description>Intra City Charges</description>
        <label>Intra City</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Corporate Approved</fullName>
                </value>
                <value>
                    <fullName>Corporate Rejected</fullName>
                </value>
                <value>
                    <fullName>Client Approved</fullName>
                </value>
                <value>
                    <fullName>Client Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

temp/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intra_City__c</fullName>
        <inlineHelpText>Intra City charges</inlineHelpText>
        <label>Intra City</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

temp/unpackaged/classes/TestDataUtility.cls
/*------------------------------------------------------------------
* Author: Techila Global Services Pvt Ltd.
* Apex Class Name: TestDataUtility
* Created Date: 19-June-2016
* Description: Test Data Creation for TestClass
-------------------------------------------------------------------*/

@isTest
public Class TestDataUtility{
    
    public static Account objAccount; 
    public static Contact objContact;
    public static Opportunity objOpportunity;
    public static OpportunityContactRole objOCR;   
    public static Contract__c objContract; 
    public static PricebookEntry objPBE;
    public static Product2 objProduct;
    public static OpportunityLineItem OLI;
    
    // Method to create Account, its associated contacts and Opportunity
    public static Opportunity crtActOppCont(Id recType){
        objAccount= new Account();    
        objAccount.Name='Test Account';
        objAccount.Invoicing_Mode__c='Prepaid';
        objAccount.Phone__c='7798989898';
        insert objAccount;
        
        objContact= new Contact();
        objContact.FirstName='Pradeep';
        objContact.LastName='Gore';
        objContact.Email='test1@techilaservices.com';
        objContact.AccountId=objAccount.Id;
        insert objContact;
        
        objOpportunity = new Opportunity();
        objOpportunity.Name='Test opportunity1';
        objOpportunity.StageName='Commercials Agreed';
        objOpportunity.RecordTypeId=recType;
        objOpportunity.Description='test';
        objOpportunity.Sites_Listed_On__c='test1';
        objOpportunity.CloseDate=System.today();
        objOpportunity.Forward_Base__c=500;
        objOpportunity.AccountId=objAccount.Id;
        objOpportunity.Email__c = 'test@test.com';
        objOpportunity.Phone__c = '1234567890';
        objOpportunity.Volume_Potential__c = 1;
        objOpportunity.Create_Opportunity__c=true;
        objOpportunity.Co_Loader__c = 'NO';
        insert objOpportunity;
        
        objOCR= new OpportunityContactRole();
        objOCR.ContactId=objContact.Id;
        objOCR.OpportunityId=objOpportunity.Id;
        objOCR.Role='Signing Authority';
        objOCR.IsPrimary=true;
        insert objOCR;
        
        return objOpportunity;    
    }
    
    // Create Contract with associated Opportunity Id
    public static Contract__c crtContract(String type,Id OpportunityId){
        
        objContract = new Contract__c();
        objContract.Type__c= type;
        objContract.Opportunity__c=OpportunityId;
        objContract.Start_Date__c=System.today();
        objContract.Effective_Date__c=Date.Today().addDays(1);
        objContract.End_Date__c=Date.Today().addDays(5);
        objcontract.CurrencyIsoCode = 'INR';
        insert objContract;
        return objContract;
    }
    
    // Create Product with asscoiated PriceBookEntry
    public static PriceBookEntry crtProductwithPBE(String ProductName){
        ID standardPBId = Test.getStandardPricebookId();
        
        PriceBook2 objpricebookone = new PriceBook2();
        objpricebookone.Name = 'Hyperlocal';
        insert objpricebookone;
        
        objProduct = new Product2(Name=ProductName,isActive=true,Intra_City__c = 7);
        insert objProduct;
        
        objPBE=new PricebookEntry();
        objPBE.Product2Id=objProduct.Id;
        //objPBE.Name = 'Hyperlocal';
        objPBE.PriceBook2Id=standardPBId;
        objPBE.IsActive=true;
        objPBE.UnitPrice=37;
        insert objPBE;
        
        return objPBE;
    }
    
    // Create OLI with associated opportunity and PriceBookEntry
    public static OpportunityLineItem crtOLI(Opportunity objOpportunity2 ,PricebookEntry objPBE){
        OLI=new OpportunityLineItem();
        OLI.OpportunityId=objOpportunity2.id;
        OLI.PricebookEntryId=objPBE.Id;
        OLI.UnitPrice=37;
        OLI.Quantity=1;
        OLI.IsActive__c=true;
        OLI.Status__c='Draft';
        insert OLI;
        
        return OLI;
    }
    
    //Method to create B2B Price
    public static B2B_Price__c crtB2BPrice(OpportunityLineItem OLI){
        B2B_Price__c objB2Bprice = new B2B_Price__c();
        objB2Bprice.Source__c='North';
        objB2Bprice.Destination__c='North';
        objB2Bprice.Amount__c=15;
        objB2Bprice.Opportunity_Line_Item_Id__c=OLI.Id;
        insert objB2Bprice;
        
        return objB2Bprice ;
    }
    public static void productCreation(Product2 objProduct,Opportunity opportunity,Pricebook2 customPB,Category__c objCategory){        
               
        
        objCategory.Sort_Order__c=2;
        insert objCategory;
        
        objProduct.Category__c = objCategory.id;
        insert objProduct;
        
        
        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();
        
        // Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = objProduct.Id, UnitPrice = 10000, IsActive = true);
        insert standardPrice;        
        
        // Insert a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = objProduct.Id, UnitPrice = 12000, IsActive = true);
        insert customPrice;                  
        
        OpportunityLineItem OLI=new OpportunityLineItem();
        OLI.OpportunityId=opportunity.id;
        OLI.PricebookEntryId=customPrice.Id;
        OLI.UnitPrice=37;
        OLI.Quantity=1;       
        OLI.IsActive__c=false;
        OLI.Status__c='Draft';        
        insert OLI;
        OLI = [SELECT Id, Name FROM OpportunityLineItem WHERE Id =: OLI.Id];
        
        System.debug('OLI.Name-------->'+OLI.Name);
        
    }
    
}