temp/unpackaged/objects/B2B_Price__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>B2B Price</label>
    <nameField>
        <displayFormat>B2B-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Hyperlocal_Price__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Hyperlocal Price</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hyperlocal Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Updated_Product_Name__c</fullName>
        <description>Used to replace 500gm with base and Incremental weights present on Opportunity</description>
        <formula>CASE( PricebookEntry.Product2.Name , &quot;Upto 500gms&quot;,  SUBSTITUTE(
&quot;Upto 500gms&quot;, &quot;500&quot;,  Text(Opportunity.Forward_Base__c) )  , &quot;Additional 500gms&quot;,SUBSTITUTE(&quot;Additional 500gms&quot;, &quot;500&quot;,Text(Opportunity.Forward_Incremental__c)), &quot;DTO (500gms)&quot;, SUBSTITUTE(
&quot;DTO (500gms)&quot;, &quot;500&quot;, Text(Opportunity.DTO_Base__c)  ) ,&quot;DTO (Additional 500gms)&quot;,  SUBSTITUTE(&quot;DTO (Additional 500gms)&quot;, &quot;500&quot;,  Text(Opportunity.DTO_Incremental__c)), &quot;RTO (Every 500gms)&quot;, SUBSTITUTE(&quot;RTO (Every 500gms)&quot;, &quot;500&quot;,  Text(Opportunity.RTO__c) ), &quot;Additional 500gms (up to 3kgs)&quot;, SUBSTITUTE(&quot;Additional 500gms (up to 3kgs)&quot;,&quot;500&quot;, TEXT(Opportunity.Forward_Incremental__c) ), &quot;RTO (Every 1000gms)&quot;,SUBSTITUTE(&quot;RTO (Every 1000gms)&quot;,&quot;1000&quot;, TEXT(Opportunity.RTO__c)), &quot;DTO (Every 1000gms)&quot;,SUBSTITUTE(&quot;DTO (Every 1000gms)&quot;,&quot;1000&quot;,TEXT( Opportunity.DTO_Base__c )),&quot;DTO (Add 1000gms)&quot;,SUBSTITUTE(&quot;DTO (Add 1000gms)&quot;,&quot;1000&quot;,TEXT( Opportunity.DTO_Incremental__c )),&quot;DTO (1000gms)&quot;,SUBSTITUTE(&quot;DTO (1000gms)&quot;,&quot;1000&quot;,TEXT( Opportunity.DTO_Base__c )), PricebookEntry.Product2.Name)</formula>
        <label>Updated Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>IF( OR ( ISBLANK( Counter__c ),  ISNULL( Counter__c ) )    , &apos;&apos; , &apos;Version &apos; + TEXT(Counter__c) + &apos;.0&apos;)</formula>
        <label>Version</label>
        <type>Text</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/Slab_Price__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <label>Opportunity Line Item Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Slab Price</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Slab Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slab Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/classes/OpportunityLineItemTriggerUtility.cls
/*****************************************************************
* Author: Chetan Dabas.
* Class Name: OpportunityLineItemTriggerUtility
* Created Date: 15-Sept-2019
* Description: Utility class for OpportunityLineItem Trigger
*******************************************************************/
global class OpportunityLineItemTriggerUtility{ 

    //Utility class to delete all related B2B Prices when OLI gets deleted
    global static void deleteRelatedPrices(List<OpportunityLineItem> oliList){		
        for(OpportunityLineItem objOLI : oliList){
            String oliString = String.valueOf(objOLI.Id);
            if(oliString.length()<=15){
                oliString += '%';
            }
            if(objOLI.Updated_Product_Name__c=='Hyperlocal'){
                delete [SELECT id FROM Hyperlocal_Price__c WHERE Opportunity_Line_Item_Id__c like: oliString];                
            }else if(objOLI.Updated_Product_Name__c=='B2B 5*5' || objOLI.Updated_Product_Name__c=='B2B 15*15' || objOLI.Updated_Product_Name__c=='B2B Lanewise'){
                delete [SELECT id FROM B2B_Price__c WHERE Opportunity_Line_Item_Id__c like: oliString];
            }else if(objOLI.Updated_Product_Name__c=='Express Shipping' || objOLI.Updated_Product_Name__c=='Standard Shipping'){
                delete [SELECT id FROM Slab_Price__c WHERE Opportunity_Line_Item_Id__c like: oliString];
            }            
        }
          }
    global static void deleteFranchisePricing(List<OpportunityLineItem> oliList){
        System.debug('Inside the delete Franchise PRicing Method and the value of oli list is '+olilist);
        Set<Id> SetOppId = new Set<Id>();
        List<String> lstStr = new List<String>();
        for(OpportunityLineITem lstOLI:oliList){
            SetOppId.add(lstOLI.OpportunityId);
            lstStr.add(lstOLI.version__c);
        }
        List<OpportunityLineITem> lstOPPLI = [Select id,Name from OpportunityLineItem where Version__c IN :lstStr AND OpportunityID IN:SetOppId];
        if(lstOppLI !=null && lstOPPLI.size()>0)
        {
            delete lstOPPLI;
        }
    }
}