temp/unpackaged/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Accepted_Time__c</fullName>
        <label>Accepted Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement_Signed_by_User_IP_Address__c</fullName>
        <label>Agreement Signed by User IP Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Viewed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Services Agreement</fullName>
                </value>
                <value>
                    <fullName>GST Agreement</fullName>
                </value>
                <value>
                    <fullName>Gst Agreement(FTL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director__c</fullName>
        <formula>Owner.Director__r.FirstName   &amp; &quot; &quot;  &amp;   Owner.Director__r.LastName</formula>
        <label>Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registered_Name__c</fullName>
        <label>Registered Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Corporate Approved</fullName>
                </value>
                <value>
                    <fullName>Corporate Rejected</fullName>
                </value>
                <value>
                    <fullName>Client Approved</fullName>
                </value>
                <value>
                    <fullName>Client Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

temp/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Corporate Approved</fullName>
                </value>
                <value>
                    <fullName>Corporate Rejected</fullName>
                </value>
                <value>
                    <fullName>Client Approved</fullName>
                </value>
                <value>
                    <fullName>Client Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>IF( OR ( ISBLANK( Counter__c ),  ISNULL( Counter__c ) )    , &apos;&apos; , &apos;Version &apos; + TEXT(Counter__c) + &apos;.0&apos;)</formula>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_A_0_250gm__c</fullName>
        <label>Zone A 0 - 250gm</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

temp/unpackaged/classes/C2CAgreementPDFController.cls
public class C2CAgreementPDFController {
    public String OppId{get;set;}
    public Contract__c objContract{get;set;}
    public Opportunity objOpportunity{get;set;}
    Public Integer subDate{get;set;}
    public String startDate{get;set;}
    public String ipAdress{get;set;}
    public List<OpportunityContactRole> contactRoleList{get;set;}
    Public OpportunityLineItem ObjectOLI{get; set;}
    Public OpportunityLineItem ObjectOLI1{get; set;}
    Public String strProductName{get; set;}
    Public String strProductName1{get; set;}
    public C2CAgreementPDFController(ApexPages.StandardController controller)
    {
        objContract = new Contract__c();
        objOpportunity = new Opportunity(); 
        contactRoleList = new List<OpportunityContactRole>();
        OppId = ApexPages.currentPage().getParameters().get('id'); 
        ipAdress = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
        system.debug('OppId--->'+OppId);
        if(OppId !=null)
        {
            objContract = [SELECT Status__c,Agreement_Signed_by_User_IP_Address__c,Start_Date__c,End_Date__c,Accepted_Time__c,
                           Contact__r.Email,Type__c,CreatedBy.Director__c,Effective_Date__c,Opportunity__c 
                           FROM Contract__c 
                           WHERE Opportunity__c=:OppId LIMIT 1];
            objOpportunity = [SELECT id,Name,Registered_Name__c,City__c,Director__c,
                              (SELECT Contact.Name FROM OpportunityContactRoles) 
                              FROM Opportunity 
                              WHERE id =:OppId LIMIT 1];
            contactRoleList = [SELECT id,ContactId,Contact.Name 
                               FROM OpportunityContactRole 
                               WHERE OpportunityId=:oppid LIMIT 1];
            Schema.DescribesObjectResult r= OpportunityLineItem.sObjectType.getDescribe();
            String ProductName = '%Delhivery Commercial Standard - C2C%';
            String ProductName1 = '%Delhivery Commercial Express - C2C%';
        Map<String, Schema.SObjectField> mapFields = new Map<String, Schema.SObjectField>();
        mapFields=r.fields.getMap();
        String oliQuery='SELECT ';
        String fieldNames='';
        for(String apiName: mapFields.KeySet()){
            fieldNames+=apiName+',';
        }
        fieldNames =fieldNames.subString(0,fieldNames.length() - 1 );
            oliQuery = oliQuery+ fieldNames+' From OpportunityLineItem WHERE OpportunityId=:oppId AND (NAME LIKE :ProductName OR NAME LIKE :ProductName1) AND IsActive__c = true Order By Version__c DESC LIMIT 2';
          List<OpportunityLineItem> oliList= Database.Query(oliQuery);
            ObjectOLI = new OpportunityLineItem();
            ObjectOLI1 = new OpportunityLineItem();
            if(oliList.size() != 0)
            {
            ObjectOLI = oliList[0];
                ObjectOLI.Zone_A_0_250gm__c = oliList[0].Zone_A_0_250gm__c;
            System.debug('Value in the ObjectOLI is '+ObjectOLI);
            strProductName = objectOLI.Name;
            System.debug('strPRoductName is '+strProductName);
            String strOppName = objOpportunity.Name;
            System.debug('strOppName is '+strOppName);
            if(strProductName.contains(strOppName))
            {
                System.debug('if OLI Name contains Opp Name');
               strProductName= strProductName.removeStartIgnoreCase(strOppName);
                System.debug('Value of str Product Name after update is '+strPRoductName);
            }
            ObjectOLI1 = oliList[1];
            System.debug('Value in the ObjectOLI1 is '+ObjectOLI1);
            strProductName1 = objectOLI1.Name;
            System.debug('strPRoductName is '+strProductName1);
            String strOppName1 = objOpportunity.Name;
            System.debug('strOppName is '+strOppName1);
            if(strProductName1.contains(strOppName1))
            {
                System.debug('if OLI Name contains Opp Name');
               strProductName1= strProductName1.removeStartIgnoreCase(strOppName1);
                System.debug('Value of str Product Name after update is '+strPRoductName1);
            }
            }
            if(objContract.Start_Date__c !=null)
            {
            subDate = objContract.Start_Date__c.Day(); 
            Datetime dt = (Datetime)objContract.Start_Date__c; 
            startDate = dt.format('MM/dd/yyyy');
            system.debug('objOpportunity--->'+objOpportunity);
            }
        }
    }
}