temp/unpackaged/objects/Customer_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>EMAIL_POC1__c</fullName>
        <label>EMAIL POC1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMAIL_POC2__c</fullName>
        <label>EMAIL POC2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMAIL_POC3__c</fullName>
        <label>EMAIL POC3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name_POC1__c</fullName>
        <label>Name POC1</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_POC2__c</fullName>
        <label>Name POC2</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Onboardings</relationshipLabel>
        <relationshipName>Customer_Onboardings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Team__c</fullName>
        <label>POC Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North POC</fullName>
                </value>
                <value>
                    <fullName>Fashion CSM</fullName>
                </value>
                <value>
                    <fullName>West POC</fullName>
                </value>
                <value>
                    <fullName>South POC</fullName>
                </value>
                <value>
                    <fullName>LT B2C POC</fullName>
                </value>
                <value>
                    <fullName>Ravinder Thakur</fullName>
                </value>
                <value>
                    <fullName>North CSM B2B</fullName>
                </value>
                <value>
                    <fullName>West CSM B2B</fullName>
                </value>
                <value>
                    <fullName>South CSM B2B</fullName>
                </value>
                <value>
                    <fullName>East CSM B2B</fullName>
                </value>
                <value>
                    <fullName>LT CSM</fullName>
                </value>
                <value>
                    <fullName>C2C</fullName>
                </value>
                <value>
                    <fullName>Xborder Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Onboarding</label>
    <nameField>
        <displayFormat>COB-{0000000}</displayFormat>
        <label>Customer Onboarding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Director__c</fullName>
        <formula>Owner.Director__r.FirstName   &amp; &quot; &quot;  &amp;   Owner.Director__r.LastName</formula>
        <label>Director</label>
        <type>Text</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/POC_Team__c.object
<CustomObject>
    <fields>
        <fullName>Directors__c</fullName>
        <label>Director</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Members_Count__c</fullName>
        <label>Members Count</label>
        <summaryForeignKey>POC_Team_Member__c.POC_Team__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>POC Team</label>
    <nameField>
        <label>POC Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Director__c</fullName>
        <label>senior Director</label>
        <relationshipName>director</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

temp/unpackaged/classes/updatePocAssignmentExt.cls
public class updatePocAssignmentExt {
    public String CobRecordId{get;set;}
    
    public updatePocAssignmentExt(ApexPages.StandardController controller) {
        CobRecordId=ApexPages.currentPage().getParameters().get('id');
        system.debug('--CobRecordId--'+CobRecordId);
    }
    
    public PageReference checkValidation(){
        If(CobRecordId!='' && CobRecordId!=null){
            Customer_Onboarding__c objcustomer=[Select id,Name_POC1__c,Opportunity__r.OwnerId,Name_POC2__c,POC_Team__c,EMAIL_POC1__c,EMAIL_POC2__c,EMAIL_POC3__c From Customer_Onboarding__c where id=:CobRecordId limit 1 ];
            If(objcustomer!=null){
                If(objcustomer.Name_POC1__c==null || objcustomer.Name_POC2__c==null || objcustomer.EMAIL_POC1__c==null || objcustomer.EMAIL_POC1__c==null ||
                objcustomer.EMAIL_POC1__c=='' || objcustomer.EMAIL_POC1__c=='' ||objcustomer.Name_POC1__c=='' || objcustomer.Name_POC2__c=='' ){
                    List<User> userName = [select id, Name, Director__r.Name from User where id=:objcustomer.Opportunity__r.OwnerId];
                    List<POC_Team__c>listOfPoc=[select Name,Members_Count__c,Directors__c from POC_Team__c];
                    List<String> listofdirector=new List<String>();
                    system.debug('--listofdirector--'+listofdirector);
                    if(userName!=null){
                        if(userName[0].Director__r.Name!=null && userName[0].Director__r.Name!=''){
                        boolean checkdirector=false;
                           for(POC_Team__c each : listOfPoc)
                            {
                                if(each.Directors__c.contains(userName[0].Director__r.Name)){
                                    checkdirector=True;
                                }
                            }
                            if(checkdirector){
                                clsPOCAssignment.PocAssignment(CobRecordId);
                                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Confirm,'POC assignment request sent successfully'));
                            }
                            else{
                                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Opportunity owner\'s director is not present in Poc assignment'));
                            }
                        }
                        
                    }        
                }
                else{
                    
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'COB is already assigned to POC Team'));
                }
            }
        }
    return null;
    }

}