temp/unpackaged/objects/Customer_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Bird_Request_Id_Addendum__c</fullName>
        <label>Bird Request Id (Addendum)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bird_Request_Id__c</fullName>
        <label>Bird Request Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bird_Response_Message_Addendum__c</fullName>
        <label>Bird Response Message (Addendum)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bird_Response_Message__c</fullName>
        <label>Bird Response Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bird_Response_Status_Addendum__c</fullName>
        <label>Bird Response Status (Addendum)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bird_Response_Status__c</fullName>
        <label>Bird Response Status</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced to Bird</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Viewed</fullName>
                </value>
                <value>
                    <fullName>On-boarded Manually</fullName>
                </value>
                <value>
                    <fullName>Synced To HQ</fullName>
                </value>
                <value>
                    <fullName>Synced To Oracle</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Send to godam</fullName>
                </value>
                <value>
                    <fullName>Synced to Bird</fullName>
                </value>
                <value>
                    <fullName>Error HQ</fullName>
                </value>
                <value>
                    <fullName>Error Oracle</fullName>
                </value>
                <value>
                    <fullName>Error Bird</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Synced_to_Bird_As_Addendum__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced to Bird As Addendum</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Onboarding</label>
    <nameField>
        <displayFormat>COB-{0000000}</displayFormat>
        <label>Customer Onboarding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/unpackaged/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Onboarding Form</fullName>
                </value>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>Operating Batch</fullName>
                </value>
                <value>
                    <fullName>Delete Dropbox Files</fullName>
                </value>
                <value>
                    <fullName>HQ</fullName>
                </value>
                <value>
                    <fullName>Client Warehouse</fullName>
                </value>
                <value>
                    <fullName>POC HQ</fullName>
                </value>
                <value>
                    <fullName>Dropbox</fullName>
                </value>
                <value>
                    <fullName>Dropbox Upsert</fullName>
                </value>
                <value>
                    <fullName>DateWiseData</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/birdJsonResponse.cls
/*****************************************************************************************
* Author : Prakhar Goyal
* Created Date : 16-11-2018
* Description : To receive and send JSON response and save error logs of the response
* Test Class : birdPricingcheck_test
******************************************************************************************/
@RestResource(urlMapping='/api/birdResponseReceiver/*')
global with sharing class birdJsonResponse
{
    @HttpPost 
    global static birdWrapper doPost(String File_Name,boolean Success,String Message,String RequestId) {
        system.debug('File_Name--->'+File_Name);
        String filename =File_Name.substringBefore('-');
        
        if(filename!=null && Success!=null && Message!=null && RequestId!=null)
        {
            list<Customer_Onboarding__c> LstCub = new list<Customer_Onboarding__c>();
            LstCub = [select id, name,Bird_Request_Id__c,status__c,Bird_Response_Status_Addendum__c,Bird_Request_Id_Addendum__c,Bird_Response_Message_Addendum__c,File_Uploaded__c,Bird_Response_Message__c,Bird_Response_Status__c,Synced_to_Bird_As_Addendum__c from Customer_Onboarding__c where Id =:filename limit 1];
            system.debug('LstCub-->'+LstCub);
            
            List<Customer_Onboarding__History> onBoardHistory = new List<Customer_Onboarding__History>();

            if(filename != null)
            {
                onBoardHistory = [SELECT ParentId, OldValue, NewValue, Field, CreatedById, CreatedDate 
                                  FROM Customer_Onboarding__History where Field = 'Status__c' and ParentId =:filename ORDER BY createddate DESC ];
            }
            system.debug('onBoardHistory-->'+onBoardHistory);
            
           
            if(LstCub!=null && 	LstCub.size()>0)
            {
                if(LstCub[0].File_Uploaded__c == true && LstCub[0].Synced_to_Bird_As_Addendum__c == false )
                {
                    LstCub[0].Bird_Response_Message__c=Message;
                    LstCub[0].Bird_Request_Id__c=RequestId;
                    LstCub[0].Bird_Response_Status__c = string.valueof(Success);
                    
                    if(LstCub[0].Bird_Response_Status__c == 'False')
                    {
                        LstCub[0].File_Uploaded__c = false;
                        LstCub[0].Status__c = string.valueof(onBoardHistory[0].OldValue);
                    }
                }
                if(LstCub[0].File_Uploaded__c == true && LstCub[0].Synced_to_Bird_As_Addendum__c == true)
                {
                    LstCub[0].Bird_Response_Message_Addendum__c=Message;
                    LstCub[0].Bird_Request_Id_Addendum__c=RequestId;
                    LstCub[0].Bird_Response_Status_Addendum__c = string.valueof(Success);
                    
                    if(LstCub[0].Bird_Response_Status_Addendum__c == 'False')
                    {
                        LstCub[0].Synced_to_Bird_As_Addendum__c = false;
                    }
                }
                           
                Database.SaveResult[] srList = database.update(LstCub);
                
                if(srList[0].isSuccess())
                {
                    System.debug('Successfull' );
                    birdWrapper clsWrapper = new birdWrapper('200', 'Successfully Updated');
                    return clsWrapper;
                    
                }
                else
                {
                    System.debug('Failed' );
                    
                    Error_Log__c objError = new Error_Log__c();
                    objError.Error_Message__c = Message;
                    objError.Type__c = 'Bird Pricing';
                    insert objError;
                    birdWrapper clsWrapper = new birdWrapper('422', 'Request failed');
                    return clsWrapper;
                }
            } 
        }
        else
        {
            Error_Log__c objError = new Error_Log__c();
            objError.Error_Message__c = Message;
            objError.Type__c = 'Bird Pricing';
            insert objError;
            birdWrapper clsWrapper = new birdWrapper('400', 'Bad Request Error');
            return clsWrapper;
        }
        
        Error_Log__c objError = new Error_Log__c();
        objError.Error_Message__c = Message;
        objError.Type__c = 'Bird Pricing';
        insert objError;
        birdWrapper clsWrapper = new birdWrapper('400', 'Internal Server Error');
        return clsWrapper;
        
    }
    global class birdWrapper
    {
        global String Message;
        global String SuccessCode;
        
        global birdWrapper(String SuccessCode, String Message )
        {
            this.Message = Message;
            this.SuccessCode = SuccessCode;
        }
    }
    
}