temp/unpackaged/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>DropBox_Url__c</fullName>
        <label>DropBox Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsSuccess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSuccess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Onboarding Form</fullName>
                </value>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>Operating Batch</fullName>
                </value>
                <value>
                    <fullName>Delete Dropbox Files</fullName>
                </value>
                <value>
                    <fullName>HQ</fullName>
                </value>
                <value>
                    <fullName>Client Warehouse</fullName>
                </value>
                <value>
                    <fullName>POC HQ</fullName>
                </value>
                <value>
                    <fullName>Dropbox</fullName>
                </value>
                <value>
                    <fullName>Dropbox Upsert</fullName>
                </value>
                <value>
                    <fullName>DateWiseData</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DropBoxUrlCreateHandler.cls
public class DropBoxUrlCreateHandler {
    public static void createDropBoxUrl(Set<String> DropboxURL){
    	List<String> dropboxLinkList = New List<String>();
        dropboxLinkList.addAll(DropboxURL);
        system.debug('dropboxLinkList-->'+dropboxLinkList);
        for(integer i=0;i<dropboxLinkList.size();i++){
            Error_Log__c objErrorLog = New Error_Log__c();
            objErrorLog.DropBox_Url__c = dropboxLinkList[i];
            objErrorLog.IsSuccess__c = true;
            objErrorLog.Type__c = 'Delete Dropbox Files';
            insert objErrorLog;
            System.debug('objErrorLog-->'+objErrorLog);
        }
    }
}