temp/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Corporate Approved</fullName>
                </value>
                <value>
                    <fullName>Corporate Rejected</fullName>
                </value>
                <value>
                    <fullName>Client Approved</fullName>
                </value>
                <value>
                    <fullName>Client Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Client_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Large Horizontals</fullName>
                </value>
                <value>
                    <fullName>Vertical Leaders</fullName>
                </value>
                <value>
                    <fullName>Long tail e-tailers and platform sellers</fullName>
                </value>
                <value>
                    <fullName>Marketplace Vendors</fullName>
                </value>
                <value>
                    <fullName>Independent SMBs</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>FMCG</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Health,Pharma</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Office Products</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Aggregator</fullName>
                </value>
                <value>
                    <fullName>C2C</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Mail-Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

temp/unpackaged/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsCustom__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCustom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_liability_per_consignment__c</fullName>
        <label>Maximum Liability for Forward</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Corporate Approved</fullName>
                </value>
                <value>
                    <fullName>Corporate Rejected</fullName>
                </value>
                <value>
                    <fullName>Client Approved</fullName>
                </value>
                <value>
                    <fullName>Client Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

temp/unpackaged/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maximum_liability_per_consignment__c</fullName>
        <label>Maximum Liability for Forward</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

temp/unpackaged/classes/FranchisePricingExt_Test.cls
/*
 * Author Name: Chetan Dabas
* Description: Test Class for FranchisePricingExt
* Created Date: 12-08-2019
*/
@isTest
public class FranchisePricingExt_Test {
    
    
    public static Product2 crtProduct(String RecTypeDeveloperName, String ProductName){
        RecordType  rt2=[SELECT Id,DeveloperName FROM RecordType WHERE DeveloperName=:RecTypeDeveloperName AND SObjectType='Product2' ];
        
        Product2 objProduct = new Product2();
        objProduct.Name=ProductName;
        objProduct.RecordTypeId=rt2.Id;
        objProduct.Maximum_liability_per_consignment__c=5;
        return objProduct;
    }
       
     public static testMethod void FranchiseTest(){
       
       // For Surface Testing
        RecordType  rt1=[SELECT Id,DeveloperName FROM RecordType WHERE DeveloperName='C2C' AND SObjectType='Opportunity' limit 1 ];
        Opportunity objOpportunity=TestDataUtility.crtActOppCont(rt1.Id);
         objOpportunity.Sub_Category__c='Franchise';
         update objOpportunity;
        
        Product2 FranchiseExpressProduct = crtProduct('Franchise_Shipping','Delhivery Commercial Express - C2C');
        FranchiseExpressProduct.Maximum_liability_per_consignment__c=5;
        insert FranchiseExpressProduct;
        
        Product2 HyperlocalProduct = crtProduct('Hyperlocal','Hyperlocal');
        HyperlocalProduct.Maximum_liability_per_consignment__c=5;
        insert  HyperlocalProduct;
        
        Product2 FranchiseSurfaceProduct = crtProduct('Franchise_Shipping','Delhivery Commercial Standard - C2C');
        FranchiseSurfaceProduct.Maximum_liability_per_consignment__c=5;
        insert FranchiseSurfaceProduct;
        
        ID standardPBId = Test.getStandardPricebookId();

        PriceBook2 objpricebookone = new PriceBook2();
        objpricebookone.Name = 'C2C Pricing Model';
        insert objpricebookone;
        
        PricebookEntry objPBE=new PricebookEntry();
        objPBE.Product2Id=FranchiseExpressProduct.Id;
        objPBE.PriceBook2Id=standardPBId;
        objPBE.IsActive=true;
        objPBE.UnitPrice=37;
        insert objPBE;
        PricebookEntry objPBE1=new PricebookEntry();
        objPBE1.Product2Id=FranchiseSurfaceProduct.Id;
        objPBE1.PriceBook2Id=standardPBId;
        objPBE1.IsActive=true;
        objPBE1.UnitPrice=37;
        insert objPBE1;
        PricebookEntry objPBE2=new PricebookEntry();
        objPBE2.Product2Id=FranchiseExpressProduct.Id;
        objPBE2.PriceBook2Id=objpricebookone.Id;
        objPBE2.IsActive=true;
        objPBE2.UnitPrice=37;
        insert objPBE2;
        PricebookEntry objPBE21=new PricebookEntry();
        objPBE21.Product2Id=FranchiseSurfaceProduct.Id;
        objPBE21.PriceBook2Id=objpricebookone.Id;
        objPBE21.IsActive=true;
        objPBE21.UnitPrice=37;
        insert objPBE21;
        OpportunityLineItem objOLI= TestDataUtility.crtOLI(objOpportunity, objPBE2);
        objOLI.Description__c= 'Test';
        objOLI.Maximum_liability_per_consignment__c=15;
        objOLI.Status__c='Draft';
        objOLI.Quantity=100;
        objOLI.TotalPrice =1000;
        update objOLI;
         OpportunityLineItem objOLI1= TestDataUtility.crtOLI(objOpportunity, objPBE21);
        objOLI1.Description__c= 'Test';
        objOLI1.Maximum_liability_per_consignment__c=15;
        objOLI1.Status__c='Draft';
        objOLI1.Quantity=100;
        objOLI1.TotalPrice =1000;
         objOLI1.IsCustom__c=true;
        update objOLI1;
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('Id',objOpportunity.id);
        ApexPages.StandardController sc= new ApexPages.StandardController(objOpportunity);
        FranchisePricingExt objController= new FranchisePricingExt(sc);   
        objController.saveOLI();
        objOLI.Status__c='Corporate Approved';
        update objOLI;
         System.assertEquals('Corporate Approved',objOLI.Status__c);
          objOLI1.Status__c='Corporate Approved';
        update objOLI1;
                  System.assertEquals('Corporate Approved',objOLI1.Status__c);
        objController.saveOLI();
         objController.deleteOLI();
        objController.cancelOLI();
        objController.redirectToCustomPricing();
        objController.redirectToCustom();
        
        Test.stopTest();
    }
  public static testMethod void FranchiseTest1(){
       
       // For Surface Testing
        RecordType  rt1=[SELECT Id,DeveloperName FROM RecordType WHERE DeveloperName='C2C' AND SObjectType='Opportunity' limit 1 ];
        Opportunity objOpportunity=TestDataUtility.crtActOppCont(rt1.Id);
         objOpportunity.Sub_Category__c='Franchise';
         update objOpportunity;
        
        Product2 FranchiseExpressProduct = crtProduct('Franchise_Shipping','Delhivery Commercial Express - C2C');
        FranchiseExpressProduct.Maximum_liability_per_consignment__c=5;
        insert FranchiseExpressProduct;
        
        Product2 HyperlocalProduct = crtProduct('Hyperlocal','Hyperlocal');
        HyperlocalProduct.Maximum_liability_per_consignment__c=5;
        insert  HyperlocalProduct;
        
        Product2 FranchiseSurfaceProduct = crtProduct('Franchise_Shipping','Delhivery Commercial Standard - C2C');
        FranchiseSurfaceProduct.Maximum_liability_per_consignment__c=5;
        insert FranchiseSurfaceProduct;
        
        ID standardPBId = Test.getStandardPricebookId();

        PriceBook2 objpricebookone = new PriceBook2();
        objpricebookone.Name = 'C2C Pricing Model';
        insert objpricebookone;
        
        PricebookEntry objPBE=new PricebookEntry();
        objPBE.Product2Id=FranchiseExpressProduct.Id;
        objPBE.PriceBook2Id=standardPBId;
        objPBE.IsActive=true;
        objPBE.UnitPrice=37;
        insert objPBE;
        PricebookEntry objPBE1=new PricebookEntry();
        objPBE1.Product2Id=FranchiseSurfaceProduct.Id;
        objPBE1.PriceBook2Id=standardPBId;
        objPBE1.IsActive=true;
        objPBE1.UnitPrice=37;
        insert objPBE1;
        PricebookEntry objPBE2=new PricebookEntry();
        objPBE2.Product2Id=FranchiseExpressProduct.Id;
        objPBE2.PriceBook2Id=objpricebookone.Id;
        objPBE2.IsActive=true;
        objPBE2.UnitPrice=37;
        insert objPBE2;
        PricebookEntry objPBE21=new PricebookEntry();
        objPBE21.Product2Id=FranchiseSurfaceProduct.Id;
        objPBE21.PriceBook2Id=objpricebookone.Id;
        objPBE21.IsActive=true;
        objPBE21.UnitPrice=37;
        insert objPBE21;
        OpportunityLineItem objOLI= TestDataUtility.crtOLI(objOpportunity, objPBE2);
        objOLI.Description__c= 'Test';
        objOLI.Maximum_liability_per_consignment__c=15;
        objOLI.Status__c='Corporate Approved';
        objOLI.Quantity=100;
        objOLI.TotalPrice =1000;
        update objOLI;
         OpportunityLineItem objOLI1= TestDataUtility.crtOLI(objOpportunity, objPBE21);
        objOLI1.Description__c= 'Test';
        objOLI1.Maximum_liability_per_consignment__c=15;
        objOLI1.Status__c='Corporate Approved';
        objOLI1.Quantity=100;
        objOLI1.TotalPrice =1000;
         objOLI1.IsCustom__c=true;
        update objOLI1;
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('Id',objOpportunity.id);
        ApexPages.StandardController sc= new ApexPages.StandardController(objOpportunity);
        FranchisePricingExt objController= new FranchisePricingExt(sc);   
        objController.saveOLI();
        objOLI.Status__c='Corporate Approved';
        update objOLI;
         System.assertEquals('Corporate Approved',objOLI.Status__c);
          objOLI1.Status__c='Corporate Approved';
        update objOLI1;
                  System.assertEquals('Corporate Approved',objOLI1.Status__c);
        objController.saveOLI();
         objController.deleteOLI();
        objController.cancelOLI();
        objController.redirectToCustomPricing();
        objController.redirectToCustom();
        
        Test.stopTest();
    }

    
    
}